render_enhanced_chests=true
render_enhanced_signs=true
render_enhanced_bells=true
render_enhanced_beds=true
render_enhanced_shulker_boxes=true
render_enhanced_decorated_pots=true
chest_ao=false
sign_ao=false
bell_ao=true
bed_ao=false
shulker_box_ao=false
decorated_pot_ao=false
christmas_chests=allowed
sign_text_rendering=smart
experimental_chests=true
experimental_beds=true
experimental_signs=true
force_resource_pack_compat=true

