pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'elarion'

include 'dev'
include 'platform:core'
include 'addons:titles'
include 'addons:realms'
include 'addons:names'
include 'addons:offerings'
include 'addons:economy'
include 'addons:portals'
include 'addons:jail'
include 'addons:underworld'
include 'addons:worlds'
include 'addons:voicechat-hooks'
include 'addons:tablist'
include 'addons:government'
include 'addons:guilds'
include 'addons:newspapers'
include 'addons:security'
include 'addons:optimization'
include 'addons:angling'
include 'addons:angling-delight'
include 'addons:npcs'
include 'addons:mounts'
include 'addons:quests'
include 'addons:atlas'
include 'tests:gametest'
