dependencies {
    implementation(project(path: ':platform:core', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }

    [
            ':addons:titles',
            ':addons:realms',
            ':addons:names',
            ':addons:offerings',
            ':addons:economy',
            ':addons:portals',
            ':addons:jail',
            ':addons:underworld',
            ':addons:worlds',
            ':addons:voicechat-hooks',
            ':addons:tablist',
            ':addons:government',
            ':addons:groups',
            ':addons:newspapers',
            ':addons:security',
            ':addons:optimization',
            ':addons:npcs',
            ':addons:mounts',
            ':addons:quests',
            ':addons:atlas',
            ':addons:angling'
    ].each { addonPath ->
        implementation(project(path: addonPath, configuration: 'namedElements')) {
            exclude group: 'net.fabricmc.fabric-api'
        }
    }

    runtimeOnly 'org.yaml:snakeyaml:2.2'
    modRuntimeOnly 'xyz.nucleoid:fantasy:0.6.3+1.21'
    modRuntimeOnly 'software.bernie.geckolib:geckolib-fabric-1.21.1:4.8.4'
}

def genericPlayerNumber = 100 + new Random().nextInt(900)
def genericPlayerName = "Player${genericPlayerNumber}"
def genericPlayerUuid = UUID.randomUUID().toString()

loom {
    log4jConfigs.setFrom(file('log4j-elarion-dev.xml'))

    runs {
        configureEach {
            vmArg '-Dfabric-tag-conventions-v2.missingTagTranslationWarning=SILENCED'
            vmArg '-Dfabric-tag-conventions-v1.legacyTagWarning=SILENCED'
        }

        client {
            client()
            name = 'Elarion Generic Client'
            runDir = 'run/client-generic'
            vmArg '-XX:+UseZGC'
            vmArg '-XX:+ZGenerational'
            programArg '--username'
            programArg genericPlayerName
            programArg '--uuid'
            programArg genericPlayerUuid
            programArg '--accessToken'
            programArg '0'
        }

        clientOne {
            client()
            name = 'Elarion Client 1'
            runDir = 'run/client-one'
            vmArg '-XX:+UseZGC'
            vmArg '-XX:+ZGenerational'
            programArg '--username'
            programArg 'ElarionAdmin'
            programArg '--uuid'
            programArg '00000000-0000-4000-8000-000000000001'
            programArg '--accessToken'
            programArg '0'
        }

        clientTwo {
            client()
            name = 'Elarion Client 2'
            runDir = 'run/client-two'
            vmArg '-XX:+UseZGC'
            vmArg '-XX:+ZGenerational'
            programArg '--username'
            programArg 'ElarionPlayer1'
            programArg '--uuid'
            programArg '00000000-0000-4000-8000-000000000002'
            programArg '--accessToken'
            programArg '0'
        }
    }
}
