dependencies {
    implementation(project(path: ':platform:core', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }

    [
            ':addons:titles',
            ':addons:realms',
            ':addons:names',
            ':addons:offerings',
            ':addons:economy',
            ':addons:portals',
            ':addons:jail',
            ':addons:underworld',
            ':addons:worlds',
            ':addons:voicechat-hooks',
            ':addons:tablist',
            ':addons:government',
            ':addons:groups',
            ':addons:newspapers',
            ':addons:security',
            ':addons:optimization',
            ':addons:npcs',
            ':addons:mounts',
            ':addons:quests',
            ':addons:angling'
    ].each { addonPath ->
        implementation(project(path: addonPath, configuration: 'namedElements')) {
            exclude group: 'net.fabricmc.fabric-api'
        }
    }

    runtimeOnly 'org.yaml:snakeyaml:2.2'
    modRuntimeOnly 'xyz.nucleoid:fantasy:0.6.3+1.21'
    modRuntimeOnly 'software.bernie.geckolib:geckolib-fabric-1.21.1:4.8.4'
}

loom {
    runs {
        clientOne {
            client()
            name = 'Elarion Client 1'
            runDir = 'run/client-one'
            programArg '--username'
            programArg 'ElarionAdmin'
        }

        clientTwo {
            client()
            name = 'Elarion Client 2'
            runDir = 'run/client-two'
            programArg '--username'
            programArg 'ElarionPlayer1'
        }
    }
}
