dependencies {
    modImplementation(project(':platform:core')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    modImplementation(project(':addons:worlds')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    modRuntimeOnly 'xyz.nucleoid:fantasy:0.6.3+1.21'
    runtimeOnly 'org.yaml:snakeyaml:2.2'
}

loom {
    runs {
        gameTestServer {
            server()
            name = 'Elarion Game Test Server'
            runDir = 'run/gametest'
            vmArg '-Dfabric-api.gametest'
            vmArg "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.file('test-results/gametest.xml').get().asFile.absolutePath}"
        }
    }
}
