dependencies {
    implementation(project(path: ':platform:core', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:worlds', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:realms', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:economy', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:offerings', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:portals', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:npcs', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:government', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(path: ':addons:groups', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    modRuntimeOnly 'xyz.nucleoid:fantasy:0.6.3+1.21'
    runtimeOnly 'org.yaml:snakeyaml:2.2'
}

loom {
    runs {
        gameTestServer {
            server()
            name = 'Elarion Game Test Server'
            runDir = 'run/gametest'
            vmArg '-Dfabric-api.gametest'
            vmArg "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.file('test-results/gametest.xml').get().asFile.absolutePath}"
        }
    }
}
