dependencies {
    implementation(project(path: ':platform:core', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation 'org.yaml:snakeyaml:2.2'
    compileOnly(project(path: ':addons:economy', configuration: 'namedElements')) {
        exclude group: 'net.fabricmc.fabric-api'
    }

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

test {
    useJUnitPlatform()
}
