from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "addons" / "government" / "src" / "main" / "resources" / "assets" / "elarion_government" / "textures" / "gui" / "icons"
SHEET = ROOT / "build" / "tmp" / "government-icons-contact-v11.png"

TRANSPARENT = (0, 0, 0, 0)
PALETTE = {
    ".": TRANSPARENT,
    "o": (22, 13, 6, 255),
    "s": (78, 47, 20, 255),
    "g": (196, 138, 42, 255),
    "h": (255, 219, 121, 255),
    "p": (221, 176, 91, 255),
    "l": (255, 232, 154, 255),
    "n": (10, 6, 3, 255),
    "t": (32, 102, 86, 255),
    "T": (83, 212, 158, 255),
    "G": (98, 201, 135, 255),
    "D": (31, 90, 56, 255),
    "r": (224, 90, 71, 255),
    "R": (110, 37, 31, 255),
    "b": (96, 153, 224, 255),
    "B": (37, 74, 128, 255),
    "u": (175, 118, 232, 255),
    "U": (76, 45, 108, 255),
    "m": (143, 132, 112, 255),
    "w": (232, 226, 198, 255),
    "x": (5, 3, 2, 255),
}

REALM_COLORS = {
    "dark_red": (170, 0, 0, 255),
    "red": (255, 85, 85, 255),
    "gold": (255, 170, 0, 255),
    "yellow": (255, 255, 85, 255),
    "dark_green": (0, 170, 0, 255),
    "green": (85, 255, 85, 255),
    "aqua": (85, 255, 255, 255),
    "dark_aqua": (0, 170, 170, 255),
    "dark_blue": (0, 0, 170, 255),
    "blue": (85, 85, 255, 255),
    "light_purple": (255, 85, 255, 255),
    "dark_purple": (170, 0, 170, 255),
    "white": (245, 245, 245, 255),
    "gray": (170, 170, 170, 255),
    "dark_gray": (85, 85, 85, 255),
    "black": (12, 12, 12, 255),
}

# Hand-authored 16x16 matrices. The script validates and exports; it does not
# procedurally invent icon shapes.
ICONS = {
    "civic_crest": """
................
....hh..hh......
...hggggggh.....
...gllllllg.....
...glsssslg.....
...gltTTtlg.....
...gltnntlg.....
...gltTTtlg.....
...gllllllg.....
..hggggggggh....
..gttttttttg....
..gttoooottg....
..gggggggggg....
...osssssso.....
................
................
""",
    "current_votes": """
................
.....llllll.....
....lGGDDDl.....
....llllll......
...osggggggso...
..osgpppppgso...
..ogxllllllgo...
..ogxlGGDxlgo...
..ogxGGDxxgo....
..ogxllllllgo...
..ogxxxxxxxxgo..
..osggggggso....
...osssssso.....
................
................
................
""",
    "proposal": """
................
...osssssso.....
..osgllllgso....
..oglnnnllgo....
..ogllllllgo....
..oglnnnllgo....
..ogllllllgo....
..oglnnlllgo....
..ogllllrrgo....
..ogllllRRgo....
..osgllllgso....
...osggggso.....
....osssso......
................
................
................
""",
    "law": """
................
...osso..osso...
..osggsoosggso..
..oglllgglllgo..
..oglnlgolnlgo..
..oglllgolllgo..
..oglnngonnlgo..
..oglllgolllgo..
..oglllgolllgo..
..oglnngonnlgo..
..osggsoosggso..
...osso..osso...
................
................
................
................
""",
    "office": """
................
..hh...hh...hh..
..hgh..hh..hgh..
.hggghgggghgggh.
.oggggggggggggo.
.oggTGggggGTggo.
.oggggggggggggo.
.ogllllllllllgo.
..osggggggggso..
...osssssssso...
....oggggggo....
................
................
................
................
................
""",
    "leader_election": """
................
......hhh.......
.....hgggh......
....hgtTtgh.....
....ogtTgo......
.....oggo.......
...osglllgso....
..osglnnlggso...
..ogllllllggo...
..ogxGGDxxgo....
..ogxllllxgo....
..osggggggso....
...osssssso.....
................
................
................
""",
    "government_form": """
................
..hhhhhhhhhhhh..
.osggggggggggso.
..os..s..s..so..
...l..l..l..l...
...p..p..p..p...
...p..p..p..p...
...p..p..p..p...
...p..p..p..p...
...s..s..s..s...
..osggggggggso..
..hhhhhhhhhhhh..
..osssssssssso..
................
................
................
""",
    "people": """
................
.......hh.......
......hggh......
......oggo......
...hh.gggg.hh...
..hggsggggsggh..
..oggsggggsggo..
..sggsgllgsggs..
..osgsggggsgso..
...osssssss.....
.....osso.......
................
................
................
................
................
""",
    "timer": """
................
.....hhhhhh.....
...hggggggggh...
..hgllllllllgh..
..hglllnllllgh..
.hglsssnssslgh..
.hglsssnssslgh..
.hglssssnnslgh..
.hglssssssslgh..
..hgllssssllgh..
..hggllllgggh...
...hggggggh.....
.....ssss.......
................
................
................
""",
    "history": """
................
...hhhhhhhh.....
..osggggggso....
...osllllso.....
....osllso......
.....osso.......
......gg........
.....gllg.......
....gllllg......
...sgllllgs.....
..osggggggso....
...hhhhhhhh.....
....ssssss......
................
................
................
""",
    "archive": """
................
...hhhhhhhhhh...
..osggggggggso..
..ogssssssssgo..
..ogxllllllxgo..
..ogxlnnnllxgo..
..ogxllllllxgo..
..ogxxxxxxxxgo..
..ogxmmmmmmxgo..
..osggggggggso..
...osssssssso...
................
................
................
................
................
""",
    "project": """
................
...bbbbbbbb.....
..Blllllllb.....
..BllBllllb.....
..BllllBllb.....
..BllBllllb.....
..Blllllllb.....
..BllBBBBbb.....
..Blllllllb.....
..Bbbbbbbbb.....
...osgggso......
....osso........
................
................
................
................
""",
    "notice": """
................
...osssssssso...
..osgllllllgso..
..oglnnnnllgo...
..ogllllllllgo..
..oglnnnnllgo...
..ogllllllllgo..
..oglnnnnllgo...
..oglllllllggo..
..ogxxrrRxxggo..
..ogxxxRRxxggo..
..osgggggggso...
...osssssso.....
................
................
................
""",
    "realm_name": """
................
...hhhhhhhh.....
..osggggggso....
..ogllllllgo....
..oglnnnllgo....
..ogllllllgo....
..oglnnlllgo....
..ogllllllgo....
..oglnnnllgo....
..ogllllllgo....
..osggggggso....
...ossoosso.....
................
................
................
................
""",
    "realm_color": """
................
....hhhhhh......
...hggggggh.....
..hgrTgggggh....
..hgGDrrbgh.....
..hggbbUugh.....
..hgggomggh.....
..hgggggggh.....
...hgggggh......
....hgggh.......
.....os.........
................
................
................
................
................
""",
    "approve": """
................
...hhhhhhhhhh...
..hgggggggggh...
.hggxxxxxxxggh..
.hgxxxxxxxGGgh..
.hgxxxxxGGGDgh..
.hgxGGxGGDDgh...
.hgxGGGGDxxgh...
.hgxxGGDxxxgh...
.hgxxxDxxxxgh...
..hggggggggh....
...ssssssss.....
................
................
................
................
""",
    "settled": """
................
................
..........GGG...
.........GGGD...
........GGGD....
...GG..GGGD.....
..GGGGGGGD......
..DGGGGGD.......
...DGGGD........
....DDD.........
................
................
................
................
................
................
""",
    "reject": """
................
................
..rrr......rrr..
..Rrrr....rrrR..
...Rrrr..rrrR...
....RrrrrrrR....
.....RrrrrR.....
......RrrR......
......RrrR......
.....RrrrrR.....
....RrrrrrrR....
...Rrrr..rrrR...
..Rrrr....rrrR..
..rrr......rrr..
................
................
""",
}


def icon_from_pattern(pattern):
    rows = [line.strip() for line in pattern.strip("\n").splitlines()]
    if len(rows) != 16:
        raise ValueError(f"Pattern has {len(rows)} rows, expected 16")
    image = Image.new("RGBA", (16, 16), TRANSPARENT)
    pixels = image.load()
    for y, row in enumerate(rows):
        if len(row) != 16:
            raise ValueError(f"Pattern row {y} has {len(row)} columns, expected 16: {row!r}")
        for x, token in enumerate(row):
            try:
                pixels[x, y] = PALETTE[token]
            except KeyError as exc:
                raise ValueError(f"Unknown palette token {token!r} at {x},{y}") from exc
    return image


def color_swatch(color):
    image = Image.new("RGBA", (16, 16), TRANSPARENT)
    draw = ImageDraw.Draw(image)
    r, g, b, a = color
    light = (min(255, r + 62), min(255, g + 62), min(255, b + 62), a)
    mid = color
    dark = (max(0, r - 58), max(0, g - 58), max(0, b - 58), a)
    draw.rectangle([2, 2, 13, 13], fill=PALETTE["o"])
    draw.line([3, 1, 12, 1], fill=PALETTE["h"])
    draw.line([1, 3, 1, 12], fill=PALETTE["g"])
    draw.line([14, 3, 14, 12], fill=PALETTE["s"])
    draw.line([3, 14, 12, 14], fill=PALETTE["s"])
    draw.rectangle([4, 4, 11, 11], fill=mid)
    draw.line([4, 4, 11, 4], fill=light)
    draw.line([4, 4, 4, 11], fill=light)
    draw.line([4, 11, 11, 11], fill=dark)
    draw.line([11, 4, 11, 11], fill=dark)
    draw.point([(3, 3), (12, 3), (3, 12), (12, 12)], fill=PALETTE["g"])
    return image


def save_contact_sheet(images):
    SHEET.parent.mkdir(parents=True, exist_ok=True)
    names = sorted(images)
    cols = 6
    cell = 58
    rows = (len(names) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * cell, rows * cell), (16, 10, 6, 255))
    draw = ImageDraw.Draw(sheet)
    for index, name in enumerate(names):
        image = images[name].resize((32, 32), Image.Resampling.NEAREST)
        x = (index % cols) * cell + 13
        y = (index // cols) * cell + 4
        sheet.alpha_composite(image, (x, y))
        draw.text(((index % cols) * cell + 2, y + 36), name[:10], fill=(230, 190, 110, 255))
    sheet.save(SHEET)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    images = {name: icon_from_pattern(pattern) for name, pattern in ICONS.items()}
    images.update({name: color_swatch(color) for name, color in REALM_COLORS.items()})
    for name, image in images.items():
        if image.size != (16, 16):
            raise ValueError(f"{name} exported as {image.size}, expected 16x16")
        image.save(OUT / f"{name}.png")
    save_contact_sheet(images)
    print(f"Wrote {len(images)} icons to {OUT}")
    print(f"Contact sheet: {SHEET}")


if __name__ == "__main__":
    main()
